// src/constants.js

export const NIGERIAN_UNIVERSITIES = [
  "Abubakar Tafawa Balewa University, Bauchi (ATBU)", "Ahmadu Bello University, Zaria (ABU)", "Federal University Dutse, Jigawa (FUD)",
  "Federal University Dutsin-Ma, Katsina (FUDMA)", "Federal University Gashua, Yobe", "Federal University Gusau, Zamfara",
  "Federal University Kashere, Gombe (FUKASHERE)", "Federal University Lafia, Nasarawa", "Federal University Lokoja, Kogi (FULOKOJA)",
  "Federal University Ndufu-Alike, Ebonyi (FUNAI)", "Federal University Otuoke, Bayelsa (FUO)", "Federal University Oye-Ekiti (FUOYE)",
  "Federal University Wukari, Taraba (FUW)", "Federal University, Birnin Kebbi (FUBK)", "Federal University, Gombe (FUGombe)",
  "Federal University, Ikole, Ekiti (FUIKE)", "Federal University of Agriculture, Abeokuta (FUNAAB)", "Federal University of Agriculture, Makurdi (FUAM)",
  "Federal University of Agriculture, Zuru, Kebbi (FUAZ)", "Federal University of Health Sciences, Azare, Bauchi", "Federal University of Health Sciences, Ila-Orangun, Osun",
  "Federal University of Health Sciences, Otukpo, Benue", "Federal University of Petroleum Resources, Effurun (FUPRE)", "Federal University of Technology, Akure (FUTA)",
  "Federal University of Technology, Babura, Jigawa", "Federal University of Technology, Ikot Abasi, Akwa Ibom", "Federal University of Technology, Minna (FUTMinna)",
  "Federal University of Technology, Owerri (FUTO)", "Michael Okpara University of Agriculture, Umudike (MOUAU)", "Modibbo Adama University, Yola (MAU)",
  "National Open University of Nigeria, Abuja (NOUN)", "Nigerian Defence Academy, Kaduna (NDA)", "Nnamdi Azikiwe University, Awka (UNIZIK)",
  "Obafemi Awolowo University, Ile-Ife (OAU)", "University of Abuja (UNIABUJA)", "University of Benin (UNIBEN)", "University of Calabar (UNICAL)",
  "University of Ibadan (UI)", "University of Ilorin (UNILORIN)", "University of Jos (UNIJOS)", "University of Lagos (UNILAG)",
  "University of Maiduguri (UNIMAID)", "University of Nigeria, Nsukka (UNN)", "University of Port Harcourt (UNIPORT)",
  "University of Uyo (UNIUYO)", "Usmanu Danfodiyo University, Sokoto (UDUSOK)", "Abia State University, Uturu (ABSU)",
  "Adamawa State University, Mubi (ADSU)", "Adekunle Ajasin University, Akungba-Akoko (AAUA)", "Akwa Ibom State University, Ikot Akpaden (AKSU)",
  "Ambrose Alli University, Ekpoma (AAU)", "Anambra State University, Uli (ANSU)", "Bauchi State University, Gadau (BASU)",
  "Benue State University, Makurdi (BSU)", "Borno State University, Maiduguri (BOSU)", "Chukwuemeka Odumegwu Ojukwu University, Uli (COOU)",
  "Cross River University of Technology, Calabar (CRUTECH)", "Delta State University, Abraka (DELSU)", "Ebonyi State University, Abakaliki (EBSU)",
  "Edo State University Uzairue (EDSU)", "Ekiti State University, Ado-Ekiti (EKSU)", "Enugu State University of Science and Technology, Enugu (ESUT)",
  "Gombe State University, Tudun Wada (GSU)", "Ibrahim Badamasi Babangida University, Lapai (IBBU)", "Ignatius Ajuru University of Education, Port Harcourt (IAUE)",
  "Imo State University, Owerri (IMSU)", "Isoko Community University, Ozoro, Delta", "Kaduna State University, Kaduna (KASU)",
  "Kebbi State University of Science and Technology, Aliero (KSUSTA)", "Kogi State University, Anyigba (KSU)", "Kwara State University, Malete (KWASU)",
  "Ladoke Akintola University of Technology, Ogbomoso (LAUTECH)", "Lagos State University, Ojo (LASU)", "Niger Delta University, Wilberforce Island (NDU)",
  "Nasarawa State University, Keffi (NSUK)", "Ondo State University of Science and Technology, Okitipupa (OSUSTECH)", "Olabisi Onabanjo University, Ago-Iwoye (OOU)",
  "Osun State University, Osogbo (UNIOSUN)", "Oyo State Technical University, Ibadan (OYOTECH)", "Plateau State University, Bokkos (PLASU)",
  "Prince Abubakar Audu University, Anyigba, Kogi", "Rivers State University, Port Harcourt (RSU)", "Samuel Adegboyega University, Ogwa, Edo",
  "Sokoto State University (SSU)", "Sule Lamido University, Kafin Hausa, Jigawa (SLU)", "Tai Solarin University of Education, Ijagun (TASUED)",
  "Taraba State University, Jalingo (TSU)", "Umaru Musa Yar'adua University, Katsina (UMYU)", "University of Delta, Agbor (UNIDEL)",
  "Yobe State University, Damaturu (YSU)", "Zamfara State University, Talata Mafara", "Achievers University, Owo (AU)", "Adeleke University, Ede",
  "Afe Babalola University, Ado-Ekiti (ABUAD)", "African University of Science and Technology, Abuja (AUST)", "Al-Hikmah University, Ilorin",
  "Al-Qalam University, Katsina (AUK)", "American University of Nigeria, Yola (AUN)", "Augustine University Ilara, Lagos",
  "Babcock University, Ilishan-Remo (BU)", "Baze University, Abuja", "Bells University of Technology, Ota",
  "Benson Idahosa University, Benin City (BIU)", "Bowen University, Iwo", "Caleb University, Lagos", "Caritas University, Enugu",
  "Chrisland University, Owode, Ogun", "Christopher University, Mowe, Ogun", "Clifford University, Owerrinta, Abia",
  "Coal City University, Enugu", "Covenant University, Ota (CU)", "Crawford University, Igbesa, Ogun", "Crescent University, Abeokuta",
  "Crown Hill University, Eiyenkorin, Kwara", "David Umahi Federal University of Health Sciences, Uburu, Ebonyi", "Dominican University, Ibadan",
  "Edwin Clark University, Kiagbodo, Delta", "El-Amin University, Minna, Niger", "Elizade University, Ilara-Mokin, Ondo",
  "Evangel University, Akaeze, Ebonyi", "Fountain University, Osogbo", "Glorious Vision University, Ogwa, Edo",
  "Godfrey Okoye University, Enugu", "Gregory University, Uturu, Abia", "Hallmark University, Ijebu-Itele, Ogun",
  "Hezekiah University, Umudi, Imo", "Igbinedion University, Okada, Edo", "Joseph Ayo Babalola University, Ikeji-Arakeji (JABU)",
  "Kings University, Ode-Omu, Osun", "Kola Daisi University, Ibadan, Oyo", "Kwararafa University, Wukari, Taraba",
  "Landmark University, Omu-Aran (LMU)", "Lead City University, Ibadan", "Legacy University, Okija, Anambra",
  "Lifeforte International University, Ibadan", "Madonna University, Okija (MU)", "Mcpherson University, Seriki Sotayo, Ogun",
  "Micheal and Cecilia Ibru University, Owhrode, Delta", "Mountain Top University, Lagos", "Newgate University, Minna, Niger",
  "Nigeria-Turkish Nile University, Abuja (NTNU)", "Novena University, Ogume, Delta", "Oduduwa University, Ipetumodu, Osun",
  "Olabisi Onabanjo University (Private wing), Ogun", "Pan-Atlantic University, Lagos", "Paul University, Awka, Anambra",
  "Peaceland College of Education, Enugu", "Precious Cornerstone University, Ibadan", "Redeemer's University, Ede (RUN)",
  "Renaissance University, Enugu", "Rhema University, Obeama-Asa, Rivers", "Ritman University, Ikot Epene, Akwa Ibom",
  "Salem University, Lokoja (SU)", "Skyline University Nigeria, Kano", "Southwestern University, Oku Owa, Ogun",
  "Spiritan University, Nneochi, Abia", "St. Albert the Great University, Kwara", "Summit University, Offa, Kwara",
  "Tansian University, Umunya, Anambra", "Thomas Adewumi University, Oko, Kwara", "University of Mkar, Mkar, Benue",
  "Veritas University, Abuja", "Wellspring University, Evbuobanosa, Edo", "Wesley University, Ondo",
  "Western Delta University, Oghara, Delta", "Westland University, Iwo, Osun",
].sort();

export const FUTA_FACULTIES = [
  "SESE", "SIMME", "SLS", "SOC", "SPS", "SAAT", "SBMS", "SLIT", "SEMS", "SET"
];

export const isFUTA = (uni) => !!(uni && uni.includes("Federal University of Technology, Akure"));